name: pawcamkz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.0
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  webview_flutter: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/